name: Build and Push Docker Image

on:
  push:
    branches: [ main]
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  Build-And-Push-To-DockerHub:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Building Docker Image
        run: docker build . -t ${{ vars.DOCKER_USER }}/diabetes-prediction-mlops-project:1.0.${{ github.run_number }}

      - name: Pushing Docker Image
        run: docker push ${{ vars.DOCKER_USER }}/diabetes-prediction-mlops-project:1.0.${{ github.run_number }}
